POST http://localhost:4000/category
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2YWE5Nzc3NzQ1NzkzYzJjNTNjZDYxMzciLCJlbWFpbCI6InBhbmR5YUBnbWFpbC5jb20iLCJyb2xlIjoxLCJpYXQiOjE3ODk4MTUzNzcsImV4cCI6MTc4OTkwMTc3N30.YQdzosULT8SCAk1wun_GNcmGNbt7dbLXXJy67SU185M
Content-Type: application/json
{
    "name":"Postgres SQL"
}



GET http://localhost:4000/category/postgress-data

PUT http://localhost:4000/category/6aae757e58e4e4e0622f18d6
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2YWE5Nzc3NzQ1NzkzYzJjNTNjZDYxMzciLCJlbWFpbCI6InBhbmR5YUBnbWFpbC5jb20iLCJyb2xlIjoxLCJpYXQiOjE3ODk4MTUzNzcsImV4cCI6MTc4OTkwMTc3N30.YQdzosULT8SCAk1wun_GNcmGNbt7dbLXXJy67SU185M
Content-Type: application/json
{
    "_id":"6aaecb3895463935cb674741",
    "name":"Postgress data"
}


GET http://localhost:4000/category

DELETE http://localhost:4000/category/6aae757e58e4e4e0622f18d6
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2YWE5Nzc3NzQ1NzkzYzJjNTNjZDYxMzciLCJlbWFpbCI6InBhbmR5YUBnbWFpbC5jb20iLCJyb2xlIjoxLCJpYXQiOjE3ODk4MTUzNzcsImV4cCI6MTc4OTkwMTc3N30.YQdzosULT8SCAk1wun_GNcmGNbt7dbLXXJy67SU185M
