GET http://localhost:4000/secret
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2YWE5Nzc3NzQ1NzkzYzJjNTNjZDYxMzciLCJlbWFpbCI6InBhbmR5YUBnbWFpbC5jb20iLCJyb2xlIjoxLCJpYXQiOjE3ODk4MTI4MDcsImV4cCI6MTc4OTg5OTIwN30.5aeetN5CWNRSA0XaiFz0Iywt_Md8Kwvt1Ktzz6ogecA